//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int MaAd { get; set; }
        public string HoTenAd { get; set; }
        public string TaiKhoanAd { get; set; }
        public string MatKhauAd { get; set; }
        public string EmailAd { get; set; }
        public string DiaChiAd { get; set; }
        public Nullable<int> DienThoaiAd { get; set; }
        public string GioiTinhAd { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    }
}
