//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int MaSach { get; set; }
        public int MaDanhGia { get; set; }
        public string cmtDanhGia { get; set; }
        public Nullable<double> DiemDG { get; set; }
        public string TenKhachHang { get; set; }
        public Nullable<System.DateTime> NgayCmt { get; set; }
    
        public virtual Sach Sach { get; set; }
    }
}
