//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QuanLyBanSachModel", "FK_ChiTietDonHang_DonHang", "DonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineBooks.Models.DonHang), "ChiTietDonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineBooks.Models.ChiTietDonHang), true)]
[assembly: EdmRelationshipAttribute("QuanLyBanSachModel", "FK_ChiTietDonHang_Sach", "Sach", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineBooks.Models.Sach), "ChiTietDonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineBooks.Models.ChiTietDonHang), true)]
[assembly: EdmRelationshipAttribute("QuanLyBanSachModel", "FK_Sach_ChuDe", "ChuDe", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(OnlineBooks.Models.ChuDe), "Sach", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineBooks.Models.Sach), true)]
[assembly: EdmRelationshipAttribute("QuanLyBanSachModel", "FK_DanhGia_Sach", "Sach", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineBooks.Models.Sach), "DanhGia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineBooks.Models.DanhGia), true)]
[assembly: EdmRelationshipAttribute("QuanLyBanSachModel", "FK_DonHang_KhachHang", "KhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(OnlineBooks.Models.KhachHang), "DonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineBooks.Models.DonHang), true)]
[assembly: EdmRelationshipAttribute("QuanLyBanSachModel", "FK_Sach_NhaXuatBan", "NhaXuatBan", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(OnlineBooks.Models.NhaXuatBan), "Sach", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineBooks.Models.Sach), true)]
[assembly: EdmRelationshipAttribute("QuanLyBanSachModel", "FK_ThamGia_Sach", "Sach", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineBooks.Models.Sach), "ThamGia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineBooks.Models.ThamGia), true)]
[assembly: EdmRelationshipAttribute("QuanLyBanSachModel", "FK_ThamGia_TacGia", "TacGia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineBooks.Models.TacGia), "ThamGia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineBooks.Models.ThamGia), true)]

#endregion

namespace OnlineBooks.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuanLyBanSachEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuanLyBanSachEntities1 object using the connection string found in the 'QuanLyBanSachEntities1' section of the application configuration file.
        /// </summary>
        public QuanLyBanSachEntities1() : base("name=QuanLyBanSachEntities1", "QuanLyBanSachEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanLyBanSachEntities1 object.
        /// </summary>
        public QuanLyBanSachEntities1(string connectionString) : base(connectionString, "QuanLyBanSachEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanLyBanSachEntities1 object.
        /// </summary>
        public QuanLyBanSachEntities1(EntityConnection connection) : base(connection, "QuanLyBanSachEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Admin> Admin
        {
            get
            {
                if ((_Admin == null))
                {
                    _Admin = base.CreateObjectSet<Admin>("Admin");
                }
                return _Admin;
            }
        }
        private ObjectSet<Admin> _Admin;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ChiTietDonHang> ChiTietDonHang
        {
            get
            {
                if ((_ChiTietDonHang == null))
                {
                    _ChiTietDonHang = base.CreateObjectSet<ChiTietDonHang>("ChiTietDonHang");
                }
                return _ChiTietDonHang;
            }
        }
        private ObjectSet<ChiTietDonHang> _ChiTietDonHang;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ChuDe> ChuDe
        {
            get
            {
                if ((_ChuDe == null))
                {
                    _ChuDe = base.CreateObjectSet<ChuDe>("ChuDe");
                }
                return _ChuDe;
            }
        }
        private ObjectSet<ChuDe> _ChuDe;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DanhGia> DanhGia
        {
            get
            {
                if ((_DanhGia == null))
                {
                    _DanhGia = base.CreateObjectSet<DanhGia>("DanhGia");
                }
                return _DanhGia;
            }
        }
        private ObjectSet<DanhGia> _DanhGia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DonHang> DonHang
        {
            get
            {
                if ((_DonHang == null))
                {
                    _DonHang = base.CreateObjectSet<DonHang>("DonHang");
                }
                return _DonHang;
            }
        }
        private ObjectSet<DonHang> _DonHang;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KhachHang> KhachHang
        {
            get
            {
                if ((_KhachHang == null))
                {
                    _KhachHang = base.CreateObjectSet<KhachHang>("KhachHang");
                }
                return _KhachHang;
            }
        }
        private ObjectSet<KhachHang> _KhachHang;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NhaXuatBan> NhaXuatBan
        {
            get
            {
                if ((_NhaXuatBan == null))
                {
                    _NhaXuatBan = base.CreateObjectSet<NhaXuatBan>("NhaXuatBan");
                }
                return _NhaXuatBan;
            }
        }
        private ObjectSet<NhaXuatBan> _NhaXuatBan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sach> Sach
        {
            get
            {
                if ((_Sach == null))
                {
                    _Sach = base.CreateObjectSet<Sach>("Sach");
                }
                return _Sach;
            }
        }
        private ObjectSet<Sach> _Sach;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TacGia> TacGia
        {
            get
            {
                if ((_TacGia == null))
                {
                    _TacGia = base.CreateObjectSet<TacGia>("TacGia");
                }
                return _TacGia;
            }
        }
        private ObjectSet<TacGia> _TacGia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ThamGia> ThamGia
        {
            get
            {
                if ((_ThamGia == null))
                {
                    _ThamGia = base.CreateObjectSet<ThamGia>("ThamGia");
                }
                return _ThamGia;
            }
        }
        private ObjectSet<ThamGia> _ThamGia;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Admin EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdmin(Admin admin)
        {
            base.AddObject("Admin", admin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChiTietDonHang EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChiTietDonHang(ChiTietDonHang chiTietDonHang)
        {
            base.AddObject("ChiTietDonHang", chiTietDonHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChuDe EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChuDe(ChuDe chuDe)
        {
            base.AddObject("ChuDe", chuDe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DanhGia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDanhGia(DanhGia danhGia)
        {
            base.AddObject("DanhGia", danhGia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DonHang EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDonHang(DonHang donHang)
        {
            base.AddObject("DonHang", donHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KhachHang EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhachHang(KhachHang khachHang)
        {
            base.AddObject("KhachHang", khachHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhaXuatBan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhaXuatBan(NhaXuatBan nhaXuatBan)
        {
            base.AddObject("NhaXuatBan", nhaXuatBan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sach EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSach(Sach sach)
        {
            base.AddObject("Sach", sach);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TacGia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTacGia(TacGia tacGia)
        {
            base.AddObject("TacGia", tacGia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ThamGia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThamGia(ThamGia thamGia)
        {
            base.AddObject("ThamGia", thamGia);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="Admin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Admin object.
        /// </summary>
        /// <param name="maAd">Initial value of the MaAd property.</param>
        public static Admin CreateAdmin(global::System.Int32 maAd)
        {
            Admin admin = new Admin();
            admin.MaAd = maAd;
            return admin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaAd
        {
            get
            {
                return _MaAd;
            }
            set
            {
                if (_MaAd != value)
                {
                    OnMaAdChanging(value);
                    ReportPropertyChanging("MaAd");
                    _MaAd = StructuralObject.SetValidValue(value, "MaAd");
                    ReportPropertyChanged("MaAd");
                    OnMaAdChanged();
                }
            }
        }
        private global::System.Int32 _MaAd;
        partial void OnMaAdChanging(global::System.Int32 value);
        partial void OnMaAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTenAd
        {
            get
            {
                return _HoTenAd;
            }
            set
            {
                OnHoTenAdChanging(value);
                ReportPropertyChanging("HoTenAd");
                _HoTenAd = StructuralObject.SetValidValue(value, true, "HoTenAd");
                ReportPropertyChanged("HoTenAd");
                OnHoTenAdChanged();
            }
        }
        private global::System.String _HoTenAd;
        partial void OnHoTenAdChanging(global::System.String value);
        partial void OnHoTenAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaiKhoanAd
        {
            get
            {
                return _TaiKhoanAd;
            }
            set
            {
                OnTaiKhoanAdChanging(value);
                ReportPropertyChanging("TaiKhoanAd");
                _TaiKhoanAd = StructuralObject.SetValidValue(value, true, "TaiKhoanAd");
                ReportPropertyChanged("TaiKhoanAd");
                OnTaiKhoanAdChanged();
            }
        }
        private global::System.String _TaiKhoanAd;
        partial void OnTaiKhoanAdChanging(global::System.String value);
        partial void OnTaiKhoanAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MatKhauAd
        {
            get
            {
                return _MatKhauAd;
            }
            set
            {
                OnMatKhauAdChanging(value);
                ReportPropertyChanging("MatKhauAd");
                _MatKhauAd = StructuralObject.SetValidValue(value, true, "MatKhauAd");
                ReportPropertyChanged("MatKhauAd");
                OnMatKhauAdChanged();
            }
        }
        private global::System.String _MatKhauAd;
        partial void OnMatKhauAdChanging(global::System.String value);
        partial void OnMatKhauAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAd
        {
            get
            {
                return _EmailAd;
            }
            set
            {
                OnEmailAdChanging(value);
                ReportPropertyChanging("EmailAd");
                _EmailAd = StructuralObject.SetValidValue(value, true, "EmailAd");
                ReportPropertyChanged("EmailAd");
                OnEmailAdChanged();
            }
        }
        private global::System.String _EmailAd;
        partial void OnEmailAdChanging(global::System.String value);
        partial void OnEmailAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChiAd
        {
            get
            {
                return _DiaChiAd;
            }
            set
            {
                OnDiaChiAdChanging(value);
                ReportPropertyChanging("DiaChiAd");
                _DiaChiAd = StructuralObject.SetValidValue(value, true, "DiaChiAd");
                ReportPropertyChanged("DiaChiAd");
                OnDiaChiAdChanged();
            }
        }
        private global::System.String _DiaChiAd;
        partial void OnDiaChiAdChanging(global::System.String value);
        partial void OnDiaChiAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DienThoaiAd
        {
            get
            {
                return _DienThoaiAd;
            }
            set
            {
                OnDienThoaiAdChanging(value);
                ReportPropertyChanging("DienThoaiAd");
                _DienThoaiAd = StructuralObject.SetValidValue(value, "DienThoaiAd");
                ReportPropertyChanged("DienThoaiAd");
                OnDienThoaiAdChanged();
            }
        }
        private Nullable<global::System.Int32> _DienThoaiAd;
        partial void OnDienThoaiAdChanging(Nullable<global::System.Int32> value);
        partial void OnDienThoaiAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GioiTinhAd
        {
            get
            {
                return _GioiTinhAd;
            }
            set
            {
                OnGioiTinhAdChanging(value);
                ReportPropertyChanging("GioiTinhAd");
                _GioiTinhAd = StructuralObject.SetValidValue(value, true, "GioiTinhAd");
                ReportPropertyChanged("GioiTinhAd");
                OnGioiTinhAdChanged();
            }
        }
        private global::System.String _GioiTinhAd;
        partial void OnGioiTinhAdChanging(global::System.String value);
        partial void OnGioiTinhAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgaySinh
        {
            get
            {
                return _NgaySinh;
            }
            set
            {
                OnNgaySinhChanging(value);
                ReportPropertyChanging("NgaySinh");
                _NgaySinh = StructuralObject.SetValidValue(value, "NgaySinh");
                ReportPropertyChanged("NgaySinh");
                OnNgaySinhChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgaySinh;
        partial void OnNgaySinhChanging(Nullable<global::System.DateTime> value);
        partial void OnNgaySinhChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="ChiTietDonHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChiTietDonHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ChiTietDonHang object.
        /// </summary>
        /// <param name="maDonHang">Initial value of the MaDonHang property.</param>
        /// <param name="maSach">Initial value of the MaSach property.</param>
        public static ChiTietDonHang CreateChiTietDonHang(global::System.Int32 maDonHang, global::System.Int32 maSach)
        {
            ChiTietDonHang chiTietDonHang = new ChiTietDonHang();
            chiTietDonHang.MaDonHang = maDonHang;
            chiTietDonHang.MaSach = maSach;
            return chiTietDonHang;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaDonHang
        {
            get
            {
                return _MaDonHang;
            }
            set
            {
                if (_MaDonHang != value)
                {
                    OnMaDonHangChanging(value);
                    ReportPropertyChanging("MaDonHang");
                    _MaDonHang = StructuralObject.SetValidValue(value, "MaDonHang");
                    ReportPropertyChanged("MaDonHang");
                    OnMaDonHangChanged();
                }
            }
        }
        private global::System.Int32 _MaDonHang;
        partial void OnMaDonHangChanging(global::System.Int32 value);
        partial void OnMaDonHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaSach
        {
            get
            {
                return _MaSach;
            }
            set
            {
                if (_MaSach != value)
                {
                    OnMaSachChanging(value);
                    ReportPropertyChanging("MaSach");
                    _MaSach = StructuralObject.SetValidValue(value, "MaSach");
                    ReportPropertyChanged("MaSach");
                    OnMaSachChanged();
                }
            }
        }
        private global::System.Int32 _MaSach;
        partial void OnMaSachChanging(global::System.Int32 value);
        partial void OnMaSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLuong
        {
            get
            {
                return _SoLuong;
            }
            set
            {
                OnSoLuongChanging(value);
                ReportPropertyChanging("SoLuong");
                _SoLuong = StructuralObject.SetValidValue(value, "SoLuong");
                ReportPropertyChanged("SoLuong");
                OnSoLuongChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLuong;
        partial void OnSoLuongChanging(Nullable<global::System.Int32> value);
        partial void OnSoLuongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DonGia
        {
            get
            {
                return _DonGia;
            }
            set
            {
                OnDonGiaChanging(value);
                ReportPropertyChanging("DonGia");
                _DonGia = StructuralObject.SetValidValue(value, true, "DonGia");
                ReportPropertyChanged("DonGia");
                OnDonGiaChanged();
            }
        }
        private global::System.String _DonGia;
        partial void OnDonGiaChanging(global::System.String value);
        partial void OnDonGiaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_ChiTietDonHang_DonHang", "DonHang")]
        public DonHang DonHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DonHang>("QuanLyBanSachModel.FK_ChiTietDonHang_DonHang", "DonHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DonHang>("QuanLyBanSachModel.FK_ChiTietDonHang_DonHang", "DonHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DonHang> DonHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DonHang>("QuanLyBanSachModel.FK_ChiTietDonHang_DonHang", "DonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DonHang>("QuanLyBanSachModel.FK_ChiTietDonHang_DonHang", "DonHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_ChiTietDonHang_Sach", "Sach")]
        public Sach Sach
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sach>("QuanLyBanSachModel.FK_ChiTietDonHang_Sach", "Sach").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sach>("QuanLyBanSachModel.FK_ChiTietDonHang_Sach", "Sach").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sach> SachReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sach>("QuanLyBanSachModel.FK_ChiTietDonHang_Sach", "Sach");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sach>("QuanLyBanSachModel.FK_ChiTietDonHang_Sach", "Sach", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="ChuDe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChuDe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ChuDe object.
        /// </summary>
        /// <param name="maChuDe">Initial value of the MaChuDe property.</param>
        public static ChuDe CreateChuDe(global::System.Int32 maChuDe)
        {
            ChuDe chuDe = new ChuDe();
            chuDe.MaChuDe = maChuDe;
            return chuDe;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaChuDe
        {
            get
            {
                return _MaChuDe;
            }
            set
            {
                if (_MaChuDe != value)
                {
                    OnMaChuDeChanging(value);
                    ReportPropertyChanging("MaChuDe");
                    _MaChuDe = StructuralObject.SetValidValue(value, "MaChuDe");
                    ReportPropertyChanged("MaChuDe");
                    OnMaChuDeChanged();
                }
            }
        }
        private global::System.Int32 _MaChuDe;
        partial void OnMaChuDeChanging(global::System.Int32 value);
        partial void OnMaChuDeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenChuDe
        {
            get
            {
                return _TenChuDe;
            }
            set
            {
                OnTenChuDeChanging(value);
                ReportPropertyChanging("TenChuDe");
                _TenChuDe = StructuralObject.SetValidValue(value, true, "TenChuDe");
                ReportPropertyChanged("TenChuDe");
                OnTenChuDeChanged();
            }
        }
        private global::System.String _TenChuDe;
        partial void OnTenChuDeChanging(global::System.String value);
        partial void OnTenChuDeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_Sach_ChuDe", "Sach")]
        public EntityCollection<Sach> Sach
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sach>("QuanLyBanSachModel.FK_Sach_ChuDe", "Sach");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sach>("QuanLyBanSachModel.FK_Sach_ChuDe", "Sach", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="DanhGia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DanhGia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DanhGia object.
        /// </summary>
        /// <param name="maSach">Initial value of the MaSach property.</param>
        /// <param name="maDanhGia">Initial value of the MaDanhGia property.</param>
        public static DanhGia CreateDanhGia(global::System.Int32 maSach, global::System.Int32 maDanhGia)
        {
            DanhGia danhGia = new DanhGia();
            danhGia.MaSach = maSach;
            danhGia.MaDanhGia = maDanhGia;
            return danhGia;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaSach
        {
            get
            {
                return _MaSach;
            }
            set
            {
                if (_MaSach != value)
                {
                    OnMaSachChanging(value);
                    ReportPropertyChanging("MaSach");
                    _MaSach = StructuralObject.SetValidValue(value, "MaSach");
                    ReportPropertyChanged("MaSach");
                    OnMaSachChanged();
                }
            }
        }
        private global::System.Int32 _MaSach;
        partial void OnMaSachChanging(global::System.Int32 value);
        partial void OnMaSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaDanhGia
        {
            get
            {
                return _MaDanhGia;
            }
            set
            {
                if (_MaDanhGia != value)
                {
                    OnMaDanhGiaChanging(value);
                    ReportPropertyChanging("MaDanhGia");
                    _MaDanhGia = StructuralObject.SetValidValue(value, "MaDanhGia");
                    ReportPropertyChanged("MaDanhGia");
                    OnMaDanhGiaChanged();
                }
            }
        }
        private global::System.Int32 _MaDanhGia;
        partial void OnMaDanhGiaChanging(global::System.Int32 value);
        partial void OnMaDanhGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cmtDanhGia
        {
            get
            {
                return _cmtDanhGia;
            }
            set
            {
                OncmtDanhGiaChanging(value);
                ReportPropertyChanging("cmtDanhGia");
                _cmtDanhGia = StructuralObject.SetValidValue(value, true, "cmtDanhGia");
                ReportPropertyChanged("cmtDanhGia");
                OncmtDanhGiaChanged();
            }
        }
        private global::System.String _cmtDanhGia;
        partial void OncmtDanhGiaChanging(global::System.String value);
        partial void OncmtDanhGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DiemDG
        {
            get
            {
                return _DiemDG;
            }
            set
            {
                OnDiemDGChanging(value);
                ReportPropertyChanging("DiemDG");
                _DiemDG = StructuralObject.SetValidValue(value, "DiemDG");
                ReportPropertyChanged("DiemDG");
                OnDiemDGChanged();
            }
        }
        private Nullable<global::System.Double> _DiemDG;
        partial void OnDiemDGChanging(Nullable<global::System.Double> value);
        partial void OnDiemDGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenKhachHang
        {
            get
            {
                return _TenKhachHang;
            }
            set
            {
                OnTenKhachHangChanging(value);
                ReportPropertyChanging("TenKhachHang");
                _TenKhachHang = StructuralObject.SetValidValue(value, true, "TenKhachHang");
                ReportPropertyChanged("TenKhachHang");
                OnTenKhachHangChanged();
            }
        }
        private global::System.String _TenKhachHang;
        partial void OnTenKhachHangChanging(global::System.String value);
        partial void OnTenKhachHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayCmt
        {
            get
            {
                return _NgayCmt;
            }
            set
            {
                OnNgayCmtChanging(value);
                ReportPropertyChanging("NgayCmt");
                _NgayCmt = StructuralObject.SetValidValue(value, "NgayCmt");
                ReportPropertyChanged("NgayCmt");
                OnNgayCmtChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayCmt;
        partial void OnNgayCmtChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayCmtChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_DanhGia_Sach", "Sach")]
        public Sach Sach
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sach>("QuanLyBanSachModel.FK_DanhGia_Sach", "Sach").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sach>("QuanLyBanSachModel.FK_DanhGia_Sach", "Sach").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sach> SachReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sach>("QuanLyBanSachModel.FK_DanhGia_Sach", "Sach");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sach>("QuanLyBanSachModel.FK_DanhGia_Sach", "Sach", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="DonHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DonHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DonHang object.
        /// </summary>
        /// <param name="maDonHang">Initial value of the MaDonHang property.</param>
        public static DonHang CreateDonHang(global::System.Int32 maDonHang)
        {
            DonHang donHang = new DonHang();
            donHang.MaDonHang = maDonHang;
            return donHang;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaDonHang
        {
            get
            {
                return _MaDonHang;
            }
            set
            {
                if (_MaDonHang != value)
                {
                    OnMaDonHangChanging(value);
                    ReportPropertyChanging("MaDonHang");
                    _MaDonHang = StructuralObject.SetValidValue(value, "MaDonHang");
                    ReportPropertyChanged("MaDonHang");
                    OnMaDonHangChanged();
                }
            }
        }
        private global::System.Int32 _MaDonHang;
        partial void OnMaDonHangChanging(global::System.Int32 value);
        partial void OnMaDonHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DaThanhToan
        {
            get
            {
                return _DaThanhToan;
            }
            set
            {
                OnDaThanhToanChanging(value);
                ReportPropertyChanging("DaThanhToan");
                _DaThanhToan = StructuralObject.SetValidValue(value, "DaThanhToan");
                ReportPropertyChanged("DaThanhToan");
                OnDaThanhToanChanged();
            }
        }
        private Nullable<global::System.Int32> _DaThanhToan;
        partial void OnDaThanhToanChanging(Nullable<global::System.Int32> value);
        partial void OnDaThanhToanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TinhTrangGiaoHang
        {
            get
            {
                return _TinhTrangGiaoHang;
            }
            set
            {
                OnTinhTrangGiaoHangChanging(value);
                ReportPropertyChanging("TinhTrangGiaoHang");
                _TinhTrangGiaoHang = StructuralObject.SetValidValue(value, "TinhTrangGiaoHang");
                ReportPropertyChanged("TinhTrangGiaoHang");
                OnTinhTrangGiaoHangChanged();
            }
        }
        private Nullable<global::System.Int32> _TinhTrangGiaoHang;
        partial void OnTinhTrangGiaoHangChanging(Nullable<global::System.Int32> value);
        partial void OnTinhTrangGiaoHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayDat
        {
            get
            {
                return _NgayDat;
            }
            set
            {
                OnNgayDatChanging(value);
                ReportPropertyChanging("NgayDat");
                _NgayDat = StructuralObject.SetValidValue(value, "NgayDat");
                ReportPropertyChanged("NgayDat");
                OnNgayDatChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayDat;
        partial void OnNgayDatChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayDatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayGiao
        {
            get
            {
                return _NgayGiao;
            }
            set
            {
                OnNgayGiaoChanging(value);
                ReportPropertyChanging("NgayGiao");
                _NgayGiao = StructuralObject.SetValidValue(value, "NgayGiao");
                ReportPropertyChanged("NgayGiao");
                OnNgayGiaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayGiao;
        partial void OnNgayGiaoChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayGiaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                OnMaKHChanging(value);
                ReportPropertyChanging("MaKH");
                _MaKH = StructuralObject.SetValidValue(value, "MaKH");
                ReportPropertyChanged("MaKH");
                OnMaKHChanged();
            }
        }
        private Nullable<global::System.Int32> _MaKH;
        partial void OnMaKHChanging(Nullable<global::System.Int32> value);
        partial void OnMaKHChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_ChiTietDonHang_DonHang", "ChiTietDonHang")]
        public EntityCollection<ChiTietDonHang> ChiTietDonHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChiTietDonHang>("QuanLyBanSachModel.FK_ChiTietDonHang_DonHang", "ChiTietDonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChiTietDonHang>("QuanLyBanSachModel.FK_ChiTietDonHang_DonHang", "ChiTietDonHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_DonHang_KhachHang", "KhachHang")]
        public KhachHang KhachHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("QuanLyBanSachModel.FK_DonHang_KhachHang", "KhachHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("QuanLyBanSachModel.FK_DonHang_KhachHang", "KhachHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<KhachHang> KhachHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("QuanLyBanSachModel.FK_DonHang_KhachHang", "KhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<KhachHang>("QuanLyBanSachModel.FK_DonHang_KhachHang", "KhachHang", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="KhachHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KhachHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KhachHang object.
        /// </summary>
        /// <param name="maKH">Initial value of the MaKH property.</param>
        public static KhachHang CreateKhachHang(global::System.Int32 maKH)
        {
            KhachHang khachHang = new KhachHang();
            khachHang.MaKH = maKH;
            return khachHang;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                if (_MaKH != value)
                {
                    OnMaKHChanging(value);
                    ReportPropertyChanging("MaKH");
                    _MaKH = StructuralObject.SetValidValue(value, "MaKH");
                    ReportPropertyChanged("MaKH");
                    OnMaKHChanged();
                }
            }
        }
        private global::System.Int32 _MaKH;
        partial void OnMaKHChanging(global::System.Int32 value);
        partial void OnMaKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true, "HoTen");
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaiKhoan
        {
            get
            {
                return _TaiKhoan;
            }
            set
            {
                OnTaiKhoanChanging(value);
                ReportPropertyChanging("TaiKhoan");
                _TaiKhoan = StructuralObject.SetValidValue(value, true, "TaiKhoan");
                ReportPropertyChanged("TaiKhoan");
                OnTaiKhoanChanged();
            }
        }
        private global::System.String _TaiKhoan;
        partial void OnTaiKhoanChanging(global::System.String value);
        partial void OnTaiKhoanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MatKhau
        {
            get
            {
                return _MatKhau;
            }
            set
            {
                OnMatKhauChanging(value);
                ReportPropertyChanging("MatKhau");
                _MatKhau = StructuralObject.SetValidValue(value, true, "MatKhau");
                ReportPropertyChanged("MatKhau");
                OnMatKhauChanged();
            }
        }
        private global::System.String _MatKhau;
        partial void OnMatKhauChanging(global::System.String value);
        partial void OnMatKhauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true, "DiaChi");
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DienThoai
        {
            get
            {
                return _DienThoai;
            }
            set
            {
                OnDienThoaiChanging(value);
                ReportPropertyChanging("DienThoai");
                _DienThoai = StructuralObject.SetValidValue(value, true, "DienThoai");
                ReportPropertyChanged("DienThoai");
                OnDienThoaiChanged();
            }
        }
        private global::System.String _DienThoai;
        partial void OnDienThoaiChanging(global::System.String value);
        partial void OnDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value, true, "GioiTinh");
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private global::System.String _GioiTinh;
        partial void OnGioiTinhChanging(global::System.String value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgaySinh
        {
            get
            {
                return _NgaySinh;
            }
            set
            {
                OnNgaySinhChanging(value);
                ReportPropertyChanging("NgaySinh");
                _NgaySinh = StructuralObject.SetValidValue(value, "NgaySinh");
                ReportPropertyChanged("NgaySinh");
                OnNgaySinhChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgaySinh;
        partial void OnNgaySinhChanging(Nullable<global::System.DateTime> value);
        partial void OnNgaySinhChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_DonHang_KhachHang", "DonHang")]
        public EntityCollection<DonHang> DonHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DonHang>("QuanLyBanSachModel.FK_DonHang_KhachHang", "DonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DonHang>("QuanLyBanSachModel.FK_DonHang_KhachHang", "DonHang", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="NhaXuatBan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NhaXuatBan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NhaXuatBan object.
        /// </summary>
        /// <param name="maNXB">Initial value of the MaNXB property.</param>
        public static NhaXuatBan CreateNhaXuatBan(global::System.Int32 maNXB)
        {
            NhaXuatBan nhaXuatBan = new NhaXuatBan();
            nhaXuatBan.MaNXB = maNXB;
            return nhaXuatBan;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaNXB
        {
            get
            {
                return _MaNXB;
            }
            set
            {
                if (_MaNXB != value)
                {
                    OnMaNXBChanging(value);
                    ReportPropertyChanging("MaNXB");
                    _MaNXB = StructuralObject.SetValidValue(value, "MaNXB");
                    ReportPropertyChanged("MaNXB");
                    OnMaNXBChanged();
                }
            }
        }
        private global::System.Int32 _MaNXB;
        partial void OnMaNXBChanging(global::System.Int32 value);
        partial void OnMaNXBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenNXB
        {
            get
            {
                return _TenNXB;
            }
            set
            {
                OnTenNXBChanging(value);
                ReportPropertyChanging("TenNXB");
                _TenNXB = StructuralObject.SetValidValue(value, true, "TenNXB");
                ReportPropertyChanged("TenNXB");
                OnTenNXBChanged();
            }
        }
        private global::System.String _TenNXB;
        partial void OnTenNXBChanging(global::System.String value);
        partial void OnTenNXBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoDT
        {
            get
            {
                return _SoDT;
            }
            set
            {
                OnSoDTChanging(value);
                ReportPropertyChanging("SoDT");
                _SoDT = StructuralObject.SetValidValue(value, true, "SoDT");
                ReportPropertyChanged("SoDT");
                OnSoDTChanged();
            }
        }
        private global::System.String _SoDT;
        partial void OnSoDTChanging(global::System.String value);
        partial void OnSoDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true, "DiaChi");
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_Sach_NhaXuatBan", "Sach")]
        public EntityCollection<Sach> Sach
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sach>("QuanLyBanSachModel.FK_Sach_NhaXuatBan", "Sach");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sach>("QuanLyBanSachModel.FK_Sach_NhaXuatBan", "Sach", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="Sach")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sach : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sach object.
        /// </summary>
        /// <param name="maSach">Initial value of the MaSach property.</param>
        public static Sach CreateSach(global::System.Int32 maSach)
        {
            Sach sach = new Sach();
            sach.MaSach = maSach;
            return sach;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaSach
        {
            get
            {
                return _MaSach;
            }
            set
            {
                if (_MaSach != value)
                {
                    OnMaSachChanging(value);
                    ReportPropertyChanging("MaSach");
                    _MaSach = StructuralObject.SetValidValue(value, "MaSach");
                    ReportPropertyChanged("MaSach");
                    OnMaSachChanged();
                }
            }
        }
        private global::System.Int32 _MaSach;
        partial void OnMaSachChanging(global::System.Int32 value);
        partial void OnMaSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenSach
        {
            get
            {
                return _TenSach;
            }
            set
            {
                OnTenSachChanging(value);
                ReportPropertyChanging("TenSach");
                _TenSach = StructuralObject.SetValidValue(value, true, "TenSach");
                ReportPropertyChanged("TenSach");
                OnTenSachChanged();
            }
        }
        private global::System.String _TenSach;
        partial void OnTenSachChanging(global::System.String value);
        partial void OnTenSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GiaBan
        {
            get
            {
                return _GiaBan;
            }
            set
            {
                OnGiaBanChanging(value);
                ReportPropertyChanging("GiaBan");
                _GiaBan = StructuralObject.SetValidValue(value, "GiaBan");
                ReportPropertyChanged("GiaBan");
                OnGiaBanChanged();
            }
        }
        private Nullable<global::System.Decimal> _GiaBan;
        partial void OnGiaBanChanging(Nullable<global::System.Decimal> value);
        partial void OnGiaBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MoTa
        {
            get
            {
                return _MoTa;
            }
            set
            {
                OnMoTaChanging(value);
                ReportPropertyChanging("MoTa");
                _MoTa = StructuralObject.SetValidValue(value, true, "MoTa");
                ReportPropertyChanged("MoTa");
                OnMoTaChanged();
            }
        }
        private global::System.String _MoTa;
        partial void OnMoTaChanging(global::System.String value);
        partial void OnMoTaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnhBia
        {
            get
            {
                return _AnhBia;
            }
            set
            {
                OnAnhBiaChanging(value);
                ReportPropertyChanging("AnhBia");
                _AnhBia = StructuralObject.SetValidValue(value, true, "AnhBia");
                ReportPropertyChanged("AnhBia");
                OnAnhBiaChanged();
            }
        }
        private global::System.String _AnhBia;
        partial void OnAnhBiaChanging(global::System.String value);
        partial void OnAnhBiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayCapNhat
        {
            get
            {
                return _NgayCapNhat;
            }
            set
            {
                OnNgayCapNhatChanging(value);
                ReportPropertyChanging("NgayCapNhat");
                _NgayCapNhat = StructuralObject.SetValidValue(value, "NgayCapNhat");
                ReportPropertyChanged("NgayCapNhat");
                OnNgayCapNhatChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayCapNhat;
        partial void OnNgayCapNhatChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayCapNhatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLuongTon
        {
            get
            {
                return _SoLuongTon;
            }
            set
            {
                OnSoLuongTonChanging(value);
                ReportPropertyChanging("SoLuongTon");
                _SoLuongTon = StructuralObject.SetValidValue(value, "SoLuongTon");
                ReportPropertyChanged("SoLuongTon");
                OnSoLuongTonChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLuongTon;
        partial void OnSoLuongTonChanging(Nullable<global::System.Int32> value);
        partial void OnSoLuongTonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaNXB
        {
            get
            {
                return _MaNXB;
            }
            set
            {
                OnMaNXBChanging(value);
                ReportPropertyChanging("MaNXB");
                _MaNXB = StructuralObject.SetValidValue(value, "MaNXB");
                ReportPropertyChanged("MaNXB");
                OnMaNXBChanged();
            }
        }
        private Nullable<global::System.Int32> _MaNXB;
        partial void OnMaNXBChanging(Nullable<global::System.Int32> value);
        partial void OnMaNXBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaChuDe
        {
            get
            {
                return _MaChuDe;
            }
            set
            {
                OnMaChuDeChanging(value);
                ReportPropertyChanging("MaChuDe");
                _MaChuDe = StructuralObject.SetValidValue(value, "MaChuDe");
                ReportPropertyChanged("MaChuDe");
                OnMaChuDeChanged();
            }
        }
        private Nullable<global::System.Int32> _MaChuDe;
        partial void OnMaChuDeChanging(Nullable<global::System.Int32> value);
        partial void OnMaChuDeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_ChiTietDonHang_Sach", "ChiTietDonHang")]
        public EntityCollection<ChiTietDonHang> ChiTietDonHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChiTietDonHang>("QuanLyBanSachModel.FK_ChiTietDonHang_Sach", "ChiTietDonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChiTietDonHang>("QuanLyBanSachModel.FK_ChiTietDonHang_Sach", "ChiTietDonHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_Sach_ChuDe", "ChuDe")]
        public ChuDe ChuDe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChuDe>("QuanLyBanSachModel.FK_Sach_ChuDe", "ChuDe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChuDe>("QuanLyBanSachModel.FK_Sach_ChuDe", "ChuDe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ChuDe> ChuDeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChuDe>("QuanLyBanSachModel.FK_Sach_ChuDe", "ChuDe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ChuDe>("QuanLyBanSachModel.FK_Sach_ChuDe", "ChuDe", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_DanhGia_Sach", "DanhGia")]
        public EntityCollection<DanhGia> DanhGia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DanhGia>("QuanLyBanSachModel.FK_DanhGia_Sach", "DanhGia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DanhGia>("QuanLyBanSachModel.FK_DanhGia_Sach", "DanhGia", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_Sach_NhaXuatBan", "NhaXuatBan")]
        public NhaXuatBan NhaXuatBan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhaXuatBan>("QuanLyBanSachModel.FK_Sach_NhaXuatBan", "NhaXuatBan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhaXuatBan>("QuanLyBanSachModel.FK_Sach_NhaXuatBan", "NhaXuatBan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NhaXuatBan> NhaXuatBanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhaXuatBan>("QuanLyBanSachModel.FK_Sach_NhaXuatBan", "NhaXuatBan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NhaXuatBan>("QuanLyBanSachModel.FK_Sach_NhaXuatBan", "NhaXuatBan", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_ThamGia_Sach", "ThamGia")]
        public EntityCollection<ThamGia> ThamGia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ThamGia>("QuanLyBanSachModel.FK_ThamGia_Sach", "ThamGia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ThamGia>("QuanLyBanSachModel.FK_ThamGia_Sach", "ThamGia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="TacGia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TacGia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TacGia object.
        /// </summary>
        /// <param name="maTacGia">Initial value of the MaTacGia property.</param>
        public static TacGia CreateTacGia(global::System.Int32 maTacGia)
        {
            TacGia tacGia = new TacGia();
            tacGia.MaTacGia = maTacGia;
            return tacGia;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaTacGia
        {
            get
            {
                return _MaTacGia;
            }
            set
            {
                if (_MaTacGia != value)
                {
                    OnMaTacGiaChanging(value);
                    ReportPropertyChanging("MaTacGia");
                    _MaTacGia = StructuralObject.SetValidValue(value, "MaTacGia");
                    ReportPropertyChanged("MaTacGia");
                    OnMaTacGiaChanged();
                }
            }
        }
        private global::System.Int32 _MaTacGia;
        partial void OnMaTacGiaChanging(global::System.Int32 value);
        partial void OnMaTacGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenTacGia
        {
            get
            {
                return _TenTacGia;
            }
            set
            {
                OnTenTacGiaChanging(value);
                ReportPropertyChanging("TenTacGia");
                _TenTacGia = StructuralObject.SetValidValue(value, true, "TenTacGia");
                ReportPropertyChanged("TenTacGia");
                OnTenTacGiaChanged();
            }
        }
        private global::System.String _TenTacGia;
        partial void OnTenTacGiaChanging(global::System.String value);
        partial void OnTenTacGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TieuSu
        {
            get
            {
                return _TieuSu;
            }
            set
            {
                OnTieuSuChanging(value);
                ReportPropertyChanging("TieuSu");
                _TieuSu = StructuralObject.SetValidValue(value, true, "TieuSu");
                ReportPropertyChanged("TieuSu");
                OnTieuSuChanged();
            }
        }
        private global::System.String _TieuSu;
        partial void OnTieuSuChanging(global::System.String value);
        partial void OnTieuSuChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_ThamGia_TacGia", "ThamGia")]
        public EntityCollection<ThamGia> ThamGia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ThamGia>("QuanLyBanSachModel.FK_ThamGia_TacGia", "ThamGia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ThamGia>("QuanLyBanSachModel.FK_ThamGia_TacGia", "ThamGia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyBanSachModel", Name="ThamGia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ThamGia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ThamGia object.
        /// </summary>
        /// <param name="maSach">Initial value of the MaSach property.</param>
        /// <param name="maTacGia">Initial value of the MaTacGia property.</param>
        public static ThamGia CreateThamGia(global::System.Int32 maSach, global::System.Int32 maTacGia)
        {
            ThamGia thamGia = new ThamGia();
            thamGia.MaSach = maSach;
            thamGia.MaTacGia = maTacGia;
            return thamGia;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaSach
        {
            get
            {
                return _MaSach;
            }
            set
            {
                if (_MaSach != value)
                {
                    OnMaSachChanging(value);
                    ReportPropertyChanging("MaSach");
                    _MaSach = StructuralObject.SetValidValue(value, "MaSach");
                    ReportPropertyChanged("MaSach");
                    OnMaSachChanged();
                }
            }
        }
        private global::System.Int32 _MaSach;
        partial void OnMaSachChanging(global::System.Int32 value);
        partial void OnMaSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaTacGia
        {
            get
            {
                return _MaTacGia;
            }
            set
            {
                if (_MaTacGia != value)
                {
                    OnMaTacGiaChanging(value);
                    ReportPropertyChanging("MaTacGia");
                    _MaTacGia = StructuralObject.SetValidValue(value, "MaTacGia");
                    ReportPropertyChanged("MaTacGia");
                    OnMaTacGiaChanged();
                }
            }
        }
        private global::System.Int32 _MaTacGia;
        partial void OnMaTacGiaChanging(global::System.Int32 value);
        partial void OnMaTacGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VaiTro
        {
            get
            {
                return _VaiTro;
            }
            set
            {
                OnVaiTroChanging(value);
                ReportPropertyChanging("VaiTro");
                _VaiTro = StructuralObject.SetValidValue(value, true, "VaiTro");
                ReportPropertyChanged("VaiTro");
                OnVaiTroChanged();
            }
        }
        private global::System.String _VaiTro;
        partial void OnVaiTroChanging(global::System.String value);
        partial void OnVaiTroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ViTri
        {
            get
            {
                return _ViTri;
            }
            set
            {
                OnViTriChanging(value);
                ReportPropertyChanging("ViTri");
                _ViTri = StructuralObject.SetValidValue(value, true, "ViTri");
                ReportPropertyChanged("ViTri");
                OnViTriChanged();
            }
        }
        private global::System.String _ViTri;
        partial void OnViTriChanging(global::System.String value);
        partial void OnViTriChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_ThamGia_Sach", "Sach")]
        public Sach Sach
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sach>("QuanLyBanSachModel.FK_ThamGia_Sach", "Sach").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sach>("QuanLyBanSachModel.FK_ThamGia_Sach", "Sach").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sach> SachReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sach>("QuanLyBanSachModel.FK_ThamGia_Sach", "Sach");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sach>("QuanLyBanSachModel.FK_ThamGia_Sach", "Sach", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyBanSachModel", "FK_ThamGia_TacGia", "TacGia")]
        public TacGia TacGia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TacGia>("QuanLyBanSachModel.FK_ThamGia_TacGia", "TacGia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TacGia>("QuanLyBanSachModel.FK_ThamGia_TacGia", "TacGia").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TacGia> TacGiaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TacGia>("QuanLyBanSachModel.FK_ThamGia_TacGia", "TacGia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TacGia>("QuanLyBanSachModel.FK_ThamGia_TacGia", "TacGia", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
